version: '2'

services:
  mongodb-primary:
    image: 'bitnami/mongodb:latest'
    ports:
    - '27117:27017'
    environment:
    - MONGODB_REPLICA_SET_MODE=primary
    - MONGODB_ROOT_PASSWORD=123456
    - MONGODB_REPLICA_SET_KEY=replicasetkey123
  mongodb-secondary:
    image: 'bitnami/mongodb:latest'
    ports:
    - '27217:27017'
    depends_on:
    - mongodb-primary
    environment:
    - MONGODB_REPLICA_SET_MODE=secondary
    - MONGODB_PRIMARY_HOST=mongodb-primary
    - MONGODB_PRIMARY_PORT_NUMBER=27017
    - MONGODB_PRIMARY_ROOT_PASSWORD=123456
    - MONGODB_REPLICA_SET_KEY=replicasetkey123
  mongodb-arbiter:
    image: 'bitnami/mongodb:latest'
    depends_on:
    - mongodb-primary
    ports:
    - '27317:27017'
    environment:
    - MONGODB_REPLICA_SET_MODE=arbiter
    - MONGODB_PRIMARY_HOST=mongodb-primary
    - MONGODB_PRIMARY_PORT_NUMBER=27017
    - MONGODB_PRIMARY_ROOT_PASSWORD=123456
    - MONGODB_REPLICA_SET_KEY=replicasetkey123